export const INIT_PATIENTS = 'INIT_PATIENTS';
// export const INIT_PATIENTS_FAILED = 'INIT_PATIENTS_FAILED';

export const ENTRY_PROFILE_SUCCESS ='ENTRY_PROFILE_SUCCESS';
// export const FIRST_ENTRY_FAIL ='FIRST_ENTRY_FAIL';

export const TEST_COMPLETED_SUCCESS ='TEST_COMPLETED_SUCCESS';

export const TEST_STARTED = 'TEST_STARTED';
export const TEST_FINISHED = 'TEST_FINISHED';

export const HANDLE_STATUS = 'HANDLE_STATUS';
export const HANDLE_STAGE = 'HANDLE_STAGE';

export const DELETE_PATIENT = 'DELETE_PATIENT';

export const DISCHARGE_PATIENT = 'DISCHARGE_PATIENT';

export const SET_EFFICIENCY = 'SET_EFFICIENCY';

export const SET_LAST_ENTRY_DATE = 'SET_LAST_ENTRY_DATE';