export const INIT_PATIENTS = 'INIT_PATIENTS';
// export const INIT_PATIENTS_FAILED = 'INIT_PATIENTS_FAILED';

export const ENTRY_PROFILE_SUCCESS ='ENTRY_PROFILE_SUCCESS';
// export const FIRST_ENTRY_FAIL ='FIRST_ENTRY_FAIL';

export const TEST_COMPLETED_SUCCESS ='TEST_COMPLETED_SUCCESS';